name: ShellSpec
jobs:
  run_specs:
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run ShellSpec
        run: |
          curl -fsSL https://git.io/shellspec | sh -s 0.28.1 -p ./tools -y
          ./tools/lib/shellspec/bin/shellspec
